# Generated by Django 3.1.5 on 2021-01-12 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Per', 'Personal'), ('Pro', 'Professional'), ('Ent', 'Enterprise'), ('PME', 'Small Business'), ('Bus', 'Business'), ('Org', 'Organization'), ('Mag', 'Magazine')], max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('profile_bio', models.TextField(null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='profile_friends', to='user_auth.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
