# Generated by Django 3.1.4 on 2021-01-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='imagepost',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
